version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
