version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:14.17 # Use an image with the version of Node.js that matches your project
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  build-and-test-workflow:
    jobs:
      - build-and-test
